### ISSUE TITLE
Example Code is not working

### ISSUE THREAD

**Issue by Vikhyat05** [garethdmm/gryphon#37]
![Screenshot from 2019-07-01 17-41-38](https://user-images.githubusercontent.com/44644078/60435800-1d8e4a00-9c28-11e9-9274-655546fe6c2c.png)

Actually, I tried it run from the command line too and it is showing the same error. It is not able to call the base file.

**Comment by garethdmm** [comment]
Hey @Vikhyat05, if I understand correctly, the screenshot you've shown is expected behaviour. That import that is failing is for a .pyx (cython) file, so you need to import the cython importer logic before it'll work. This is the code you need to run in order to import cython files:

```
import pyximport

pyximport.install()
```

Was there another issue you were seeing when you run that file from the strategy engine? The demo code might be slightly out of date, would be good to know.

**Comment by Vikhyat05** [comment]
Thanks for your reply
Now when i tried  to run on the command line there was and import error.


Also please let me know that to run this sample strategy is it necesary for me to provide the 
API key , secerets and passphrase.

**Comment by Vikhyat05** [comment]
![Screenshot from 2019-07-02 15-46-05 (copy)](https://user-images.githubusercontent.com/44644078/60505482-70780800-9ce1-11e9-995d-80ef4491323d.png)

**Comment by garethdmm** [comment]
Ok there are a couple things going on here.

First, `gryphon-exec strategy` takes a path to a strategy file from the current working directory, and the path that you're using looks like it's wrong. Your current working directory is 'strategies' and you create the strategy in that folder, but then run `gryphon-exec strategy strategies/arb.py`. This fails because that path isn't valid. In the way you have set it up the command should just be `gryphon-exec strategy arb.py`.

Second, the currently uploaded version of gryphon only supports strategy files with the `.pyx` suffix, not `.py`. There is a fix out for this in a branch right now but for now you should use `arb.pyx` not `arb.py`.

It looks like you're a couple steps away from being able to run this strategy, if you join the [gryphon slack](https://join.slack.com/t/gryphonframework/shared_invite/enQtNjYxNjEzNTUzNzY0LTA5MWExYWM4ZTk1YTg1MzVjMTkwMDU4ZTA5ZWVmYWJmZjk1MTQ3MjdkNmZiNDQ1ODRjM2U2MTBhMjc5YWIzYWM) and join the #installation channel, I or someone else I'm sure would be happy to help you, and it would probably be faster than doing it through this issue.

**Comment by Vikhyat05** [comment]
Thanks a lot, @garethdmm for help. Now the code is working fine. Yeah, I have joined the slack group too. 
Now you can please close the issue.
